// <auto-generated />
namespace Generator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class upodobaniaaa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upodobaniaaa));
        
        string IMigrationMetadata.Id
        {
            get { return "202003022056326_upodobaniaaa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
